export const imagePath = {
logo:require('../assets/images/logo.png'),
email:require('../assets/images/icons/email.png'),
lock:require('../assets/images/icons/lock.png'),
user:require('../assets/images/icons/user.png'),
backIcon:require('../assets/images/icons/backIcon.png'),
mobile:require('../assets/images/icons/mobile.png'),
eye:require('../assets/images/icons/eye.png'),
eyeOff:require('../assets/images/icons/eyeOff.png'),
google:require('../assets/images/icons/google.png'),
applelogo:require('../assets/images/icons/applelogo.png'),
facebook:require('../assets/images/icons/facebook.png'),
insta:require('../assets/images/icons/insta.png'),
cloud:require('../assets/images/icons/cloud.png'),
search:require('../assets/images/icons/search.png'),
notificationIcon:require('../assets/images/notificationIcon.png'),
notificationIcon1:require('../assets/images/notificationIcon1.png'),
notificationIcon2:require('../assets/images/notificationIcon2.png'),
gallery:require('../assets/images/icons/gallery.png'),
edit:require('../assets/images/icons/edit.png'),
rightArrow:require('../assets/images/icons/rightArrow.png'),
cam:require('../assets/images/icons/cam.png'),
nointernet:require('../assets/images/nointernet.png'),

// Bottom Icons
home:require('../assets/images/icons/home.png'),
addPatient:require('../assets/images/icons/addPatient.png'),
notification:require('../assets/images/icons/notification.png'),
userTab:require('../assets/images/icons/userTab.png'),
bottomBg:require('../assets/images/bottomBg.png'),
checkbox_unchecked: require('../assets/images/checkbox_unchecked.png'),
checkbox_checked: require('../assets/images/checkbox_checked.png'),


};