const ScreenName = {
  WELCOME_SCREEN: 'WELCOME_SCREEN',
  LOGIN:'LOGIN',
  SIGN_UP:'SIGN_UP',
  FORGOT_PASSWORD:' ',
  OTP_VERIFICATION:'  ',
  UPDATE_PASSWORD:'   ',
  CONNECT_CLOUD:'    ',
  HOME:'HOME',
  ADD_PATIENT:'Add New Patient',
  NOTIFICATION:'Notifications',
  PROFILE:'My Account',
  EDIT_PROFILE:' My Account ',
  CHANGE_PASSWORD:'Change Password',
  TERMS:'Terms and Condition',
  HELP_CENTER:'Help Center',
  PATIENT_DETAILS:'Patient Details',
  CAMERA_GRID:'CAMERA_GRID',
  IMAGE_VIEWER:'IMAGE_VIEWER',
  IMAGE_DETAILS:'IMAGE_DETAILS',
  COLLAGE_ADD:'COLLAGE_ADD',
  EDIT_PATIENT:'Edit Patient Details',
  SELECT_PHOTO:'Select A Photo',
  FRAMING:'Framing',
  SUB_MANAGE:'SubscriptionManage',
  TAG_FILTER:'TagFilter',
};

export default ScreenName;
